### ISSUE TITLE
install xournalpp on mac os 10.11.6 El Capitan

### ISSUE THREAD

**Issue by nathalierun** [xournalpp/xournalpp#1413]
Hello,
I am totally found of xournal and I would try xournalpp.
Just see https://nathalierun.net/lycee/piwigo/  were I have every lessons wrote at school on a numerical tablet connected to my computer.

I've been working very hard for 2 days to resolve any problem to compile xournallpp from the sources. 
`cmake ..` now is ok.
`make` stops at 96% ! Here is the problem I have :
<img width="561" alt="Capture d’écran 2019-08-16 à 09 56 24" src="https://user-images.githubusercontent.com/17542520/63146494-28e8d980-c00c-11e9-9cc9-33fd5014cb47.png">
And now, I don't know what could be done.

Do I have any chance to install xournalpp on my mac ?

Thank you for any help.

**Comment by andreasb242** [comment]
Hi
macOS is not that good supported, as there are not really developers here.
cmake generates Makefiles, which are used to compile, and there are still some issues.

Can you search in the Makefile for -lCocoa? this is wrong, it should be -framework Cocoa.
And maybe you have to do this for more than for this framework.

**Comment by nathalierun** [comment]
Thank you. 
There are many Makefiles...

I think that I will let it go ;-(

**Comment by LittleHuba** [comment]
We have found the issue but are currently working on the fix as it is not that easy without a running MacOS version... Doing it in a VM brings it's own problems. 

You can contact me on Gitter and I'll be happy to point you to the right files and the potential solution.

**Comment by LittleHuba** [comment]
Fixed by #1353

**Comment by nathalierun** [comment]
Excuse me but what do I have to do know ? Just download the master again and recompile it ?
Thank you.

**Comment by LittleHuba** [comment]
Yes that is all you need to do. If it should for some reason still fail on your system feel free to comment and I'll try to solve it with you.

**Comment by nathalierun** [comment]
I still have an error when I install gtk-mac-integration
`brew install gtk-mac-integration
Updating Homebrew...
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

==> Installing dependencies for gtk-mac-integration: pygtk
==> Installing gtk-mac-integration dependency: pygtk
==> Downloading https://download.gnome.org/sources/pygtk/2.24/pygtk-2.24.0.tar.b
Already downloaded: /Users/nathalie/Library/Caches/Homebrew/downloads/c2cf44d18a1cf0cd606edda77036f020e76367dbd7b61729a8411ba9ee86c272--pygtk-2.24.0.tar.bz2
==> ./configure --prefix=/usr/local/Cellar/pygtk/2.24.0_3
==> make install
Last 15 lines from /Users/nathalie/Library/Logs/Homebrew/pygtk/02.make:
pango.c:4401:5: error: unknown type name 'PangoFontFaceClass'; did you mean 'PangoFontMapClass'?
    PangoFontFaceClass *klass = PANGO_FONT_FACE_CLASS(gclass);
    ^~~~~~~~~~~~~~~~~~
    PangoFontMapClass
/usr/local/Cellar/pango/1.44.5/include/pango-1.0/pango/pango-fontmap.h:54:35: note: 'PangoFontMapClass' declared here
typedef struct _PangoFontMapClass PangoFontMapClass;
                                  ^
pango.c:4412:20: error: no member named 'describe' in 'struct _PangoFontMapClass'
            klass->describe = _wrap_PangoFontFace__proxy_do_describe;
            ~~~~~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[1]: *** [pango_la-pango.lo] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [install-recursive] Error 1

Do not report this issue to Homebrew/brew or Homebrew/core!

/usr/local/Homebrew/Library/Homebrew/utils/github.rb:253:in `raise_api_error': GitHub Bad credentials:The GitHub credentials in the macOS keychain may be invalid. (GitHub::AuthenticationFailedError)
Clear them with:
  printf "protocol=https\nhost=github.com\n" | git credential-osxkeychain erase
Or create a personal access token:
  https://github.com/settings/tokens/new?scopes=gist,public_repo&description=Homebrew
echo 'export HOMEBREW_GITHUB_API_TOKEN=your_token_here' >> ~/.bash_profile
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:212:in `open_api'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:357:in `search'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:265:in `search_issues'
	from /usr/local/Homebrew/Library/Homebrew/utils/github.rb:278:in `issues_for_formula'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:375:in `fetch_issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:371:in `issues'
	from /usr/local/Homebrew/Library/Homebrew/exceptions.rb:425:in `dump'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:141:in `rescue in <main>'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:38:in `<main>' `

**Comment by nathalierun** [comment]
And it fails to install poppler too.

brew install poppler --verbose
Updating Homebrew...
^CWarning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

qt: macOS Sierra or newer is required.
Error: An unsatisfied requirement failed this build.

**Comment by nathalierun** [comment]
I hope I'll don't have to upgrade to Sierra !!!
How can I have a qt which could be installed ?

**Comment by LittleHuba** [comment]
Okay this unfortunately kills El Capitan completely. Poppler is a minimum requirement of Xournal++ and if it does require at least macOS Sierra then you will not be able to install Xournal++ on El Capitan.

You may try manually building the libraries by downloading the sources and compiling them by hand but the restrictions set by brew are not random and your manual build will most likely fail.

Check out [this file](https://github.com/xournalpp/xournalpp/blob/master/mac-setup/README.md) for instructions on how to build the dependencies manually.

**Comment by nathalierun** [comment]
@LittleHuba 
What a bad news !!!
If you finally succeed to build the executable file, could you send me an independant file app of xournal++ ? So I could test if it works for me ? 
It would be so wonderfull...

**Comment by LittleHuba** [comment]
Currently we only have a running pipeline with brew packages as basis. This means that we currently can't package an .app file. But the long term goal is to switch to the manual build (link in the previous message) and provide releases as .app files for macOS.

Unfortunately I do not have a macOS device and testing anything means rebuilding on the pipeline each time from scratch. This is very tedious and time consuming. So this might take a while.

But as soon as we have the releases running I'll get back to you!

**Comment by LittleHuba** [comment]
You can try this app Bundle:
https://cloud.huberulrich.de/index.php/s/MEpajkDjW3jYc2G

It was built with High Sierra. Currently the minimum-sdk was not set to 10.11 as it resulted in problems in the build process. Maybe I can solve that later on if necessary.

**Comment by nathalierun** [comment]
Thanks.
Unfortunately, it doesn't work on my computer.

<img width="772" alt="Capture d’écran 2019-08-21 à 11 40 48" src="https://user-images.githubusercontent.com/17542520/63412437-d000b300-c408-11e9-81c8-5b2bb35ff983.png">

**Comment by LittleHuba** [comment]
It seems the zip file I uploaded was wrong... The size is way to small... Please try this one instead. Fingers crossed that it works!

https://cloud.huberulrich.de/index.php/s/JbeL5c3D2zHBQA6

**Comment by LittleHuba** [comment]
Please take into account that audio features are currently not available for macOS builds as we have not included the necessary libraries into the build yet. Hopefully everything else works.

**Comment by nathalierun** [comment]
> Fingers crossed that it works!

It works @LittleHuba !!! A thousand thanks for this !

Just notice that the copy/paste doesn't work, neither with `ctrl+C` neither with `Command+C`.
It is the same with my xournal app which works inside X11.

**Comment by LittleHuba** [comment]
This might be because the gtk-mac-integration is not built for macOS 10.11.

At least we can provide releases this way, even if they do not work completely on older macOS versions.

**Comment by LittleHuba** [comment]
Small update: We have automated nightly releases for MacOS now. Feel free to check them out and report any problems you have with them.

**Comment by LittleHuba** [comment]
oh no... it seems to be buggy... The file is way too small. I'll fix this tomorrow!
