### ISSUE TITLE
Issues on startup due to error messages about directory

### ISSUE THREAD

**Issue by superenginegit** [xournalpp/xournalpp#2189]
(Please complete the following information, and then delete this line)

**Affects versions :**
 - OS: Ubuntu 20.04
 - (Linux only) Desktop environment: Gnome-Wayland
 - Which version of libgtk do you use
     3.24.20
 - Version of Xournal++: [e.g. 1.0.16, specific commit, specific branch]
     1.1.0+dev
 - Installation method: PPA

**Describe the bug**

When I start Xournal++ it shows multiple error messages about not being able to create the directory '~/.config/com.github.xournalpp.xournalpp' but the directory is already created and it also loads the config.
The first time I can close those messages, but when I want to use the tex tool it crashes and I can see in the system log that it could not create the directory for that in /tmp. After it crashes I can start it again, but then I can't close the error messages anymore.

How to reproduce the behavior:
1. Start Xournal++
2. Error messages come up

**Expected behavior**
It should just start up normally.

**Additional context**
It seems to me, that xournal++ is unable to get information about directories and can't create them either

**Comment by superenginegit** [comment]
Renaming the directory in .config does not help, but it creates a new one, but it still shows the error messages

**Comment by spbisc97** [comment]
I do have this issue too 
![image](https://user-images.githubusercontent.com/19436347/91420641-45416800-e855-11ea-8439-d27f45160c8c.png)

**Comment by Zeytun-tr** [comment]
The same problem happened with me after the last update

**Comment by spbisc97** [comment]
Yes, i just reinstalled previus version and everything seems to work fine in that version

**Comment by MuTaTeD** [comment]
> Yes, i just reinstalled previus version and everything seems to work fine in that version

please tell the procedure to install the previous version along with the version number that is working correctly

**Comment by spbisc97** [comment]
just sudo apt purge/remove/autoremove xournalpp 
and then install from here  [https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+packages?field.name_filter=&field.status_filter=&field.series_filter=focal](url)
the 18-08-2020 pachage 

or just copy and paste this in your terminal
```
sudo apt autoremove xournalpp && wget 'https://launchpad.net/~andreasbutti/+archive/ubuntu/xournalpp-master/+files/xournalpp_1.0.6-0~202008180544~ubuntu20.04.1_amd64.deb' && sudo dpkg -i xournalpp_1.0.6-0~202008180544~ubuntu20.04.1_amd64.deb
```

**Comment by MuTaTeD** [comment]
great, thanx

**Comment by spbisc97** [comment]
> great, thanx
> Although I have to run
> `sudo apt-get --fix-broken install`
> to reinstall a couple of libraries which were removed due to autoremove above

oh thanks, I changed from autoremove to just remove

**Comment by The9Cat** [comment]
Thanks @spbisc97 for posting the explicit version as a work around.  Worked for me.

**Comment by Febbe** [comment]
This bug was a regression of a huge change in filesystem handling. It is already fixed on master, but the ubuntu package seems to be created just an hour before that fix.

**Comment by superenginegit** [comment]
The Update solved it

**Comment by The9Cat** [comment]
I'm probably missing something or jumping the gun, but I just downloaded version 1.0.6-0~202008261852~ubuntu20.04.1 from the repo and it fails with the same behavior as in the OP.

**Comment by spbisc97** [comment]
Fewer problems but unfortunately I still get an error when I try to open a file 
![image](https://user-images.githubusercontent.com/19436347/91496339-40fc6580-e8bc-11ea-8e77-76659a195f1d.png)

**Comment by superenginegit** [comment]
That's strange, it works for me without issues

**Comment by Febbe** [comment]
> I have updated to latest version. 
The newest ppa? Or master? 
This issue should be at least fixed on master. For the ppa you just have to wait.
