### ISSUE TITLE
Stylus buttons in plasma wayland

### ISSUE THREAD

**Issue by voland66** [xournalpp/xournalpp#2659]
Hello,
I have tried xournal++ in the latest plasma wayland session on Fedora 33 install and encountered a problem with the stylus buttons. One of the buttons on my two button stylus performs the action it is setup to do in the settings under Eraser entry in Stylus section of settings. However, the other button is not functional, settings for Button 1 and Button 2 do not seem to affect it.
I will double check but I think I can configure both buttons in the Gnome wayland session.

If this could be fixed, it would have been great as plasma wayland is approaching level where I'm ready to switch from X11 and inability to fully use xournal++ would be one of the show stoppers in this respect.

**Comment by rolandlo** [comment]
Please check your button configurations with `xsetwacom`. Maybe you can remap your buttons.

**Comment by bhennion** [comment]
I do have a similar issue, but I haven't found the time to investigate is further yet. In my case, no buttons are functional (even though libinput detects them perfectly). I'll try to test other GtK and Qt programs to see if this comes from xournal++ or not.

> Please check your button configurations with `xsetwacom`. Maybe you can remap your buttons.

Well, xsetwacom does not support Wayland:
```
$ xsetwacom --list devices
Wayland devices found but this tool is incompatible with Wayland. See https://github.com/linuxwacom/xf86-input-wacom/wiki/Wayland
```
(we could guess that from its name xsetwacom, although xournal++ is yet another legacy exception of the x = X11 rule)

**Comment by bhennion** [comment]
Well, those tests took less time than I anticipated :-)
I believe it is a plasma-wayland issue (at least in my case). For instance, Krita (of KDE, based on Qt) detects the buttons well under Plasma X11 or Gnome Wayland, but not under Plasma Wayland. @voland66 could you confirm you have a similar behaviour (with Krita/Gimp/Inkscape or any other app of your choice)?

**Comment by voland66** [comment]
xsetwacom does not work in Wayland
-- 

Sent by my droid. Excuse his typos


Jan 13, 2021 3:18:14 AM Roland Lötscher <notifications@github.com>:

**Comment by voland66** [comment]
Yes, I do not seem to get the buttons working in other apps on wayland too. But it is even more strange -- as I said, I was able to get the eraser button working at first but it did not work today...

**Comment by Zamundaaa** [comment]
Support for tablet buttons was not implemented in KWin until 5.21. However, the eraser still doesn't work some reason

**Comment by voland66** [comment]
An update: after installing Fedora 24 with plasma 5.21 I am in the same situation as @Zamundaaa. 
My stylus has 2 buttons and no dedicated eraser tip. According to input system section of the settings xournal++ sees wacom stylus pen and wacom stylus eraser. The stylus section of the settings has entries for 2 buttons and the eraser. The setting for button 2 works as expected both in gnome and plasma on wayland. The setting for button 1 works in gnome on wayland if configured through the eraser entry in the stylus settings of xournal++. However it does not work in plasma on wayland (I have tried both button 1 and eraser entries).

**Comment by rolandlo** [comment]
@voland66 To figure out the problem you could build Xournal++ from source with the `-DDEBUG_INPUT=ON` compiler flag set, run the built Xournal++ from Terminal and report back, what is displayed if you press the non-functional button. Compare https://github.com/xournalpp/xournalpp/wiki/How-to-provide-debug-info-for-input-related-bugs

**Comment by voland66** [comment]
Here are the debug files as well as output of xinput and libinput commands.
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/6369105/debug_gdk_input.log)
[debug_input.log](https://github.com/xournalpp/xournalpp/files/6369106/debug_input.log)
[libinput-devices.txt](https://github.com/xournalpp/xournalpp/files/6369107/libinput-devices.txt)
[xinput-list.txt](https://github.com/xournalpp/xournalpp/files/6369108/xinput-list.txt)

**Comment by rolandlo** [comment]
@voland66 Did you press the stylus buttons at all? All I can see from the `debug_input.log` is that you drew on the screen with your pen repeatedly. This is what is repeated:

```
** Message: 00:04:57.705: Event
Event type:	GDK_ENTER_NOTIFY
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN

** Message: 00:04:57.739: Event
Event type:	GDK_MOTION_NOTIFY
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN

** Message: 00:04:58.000: Event
Event type:	GDK_BUTTON_PRESS          <------ you touch the screen with your pen tip
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN
Button:	1

** Message: 00:04:58.016: Event
Event type:	GDK_MOTION_NOTIFY
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN

** Message: 00:04:58.574: Event
Event type:	GDK_BUTTON_RELEASE      <--------- you leave the screen with your pen tip
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN
Button:	1

** Message: 00:04:58.581: Event
Event type:	GDK_LEAVE_NOTIFY
Source device:	GDK_SOURCE_PEN
Device Class:	INPUT_DEVICE_PEN
```

You can just run `./src/xournalpp` in the terminal without redirecting the output to a file and watch for messages when you press the stylus buttons, either when you are hovering or if you the pen tip is already on the screen. Normally you should get a message with a different button than `Button: 1`

**Comment by voland66** [comment]
I certainly pressed the button several time. After seeing your reply I also tried pressing Button 2 (which works) but I still do not see anything like `Button: 2` in the output file.
I will rebuild tomorrow and look at the output in the terminal (right now there are too many extraneous messages like `frame 0x3024a30` ).

**Comment by rolandlo** [comment]
You need to look at the output with the `DEBUG_INPUT` flag turned on and the `DEBUG_INPUT_GDK_PRINT_EVENTS` turned off, i.e.

```
cmake -UDEBUG_INPUT_GDK_PRINT_EVENTS -DDEBUG_INPUT=ON ..
cmake --build .
```

**Comment by voland66** [comment]
Sorry, the working button events appear in the log as `Button: 3`. The 1st (non-working) button events simply do not show in the log. In gnome on Wayland the 1st button events appear as `Button: 1` just like the pen but the source device is change to contain "eraser" in the name.

**Comment by Zamundaaa** [comment]
Sorry that I didn't think of writing this here sooner - it turned out to be a pretty weird bug in KWin after all, it's fixed in 5.22

**Comment by rolandlo** [comment]
@voland66 Can you confirm that upgrading KWin to 5.22 fixes the problem?

**Comment by voland66** [comment]
I will probably wait until there are fedora rpms for 5.22 or at least source rpms in the rawhide.

**Comment by voland66** [comment]
An update -- buttons do work when updated to plasma-workspace 5.22.

**Comment by ProgrammingLife** [comment]
Does xsetwacom still not work in Wayland? How to use tablet then in Wayland?

**Comment by voland66** [comment]
> Does xsetwacom still not work in Wayland? How to use tablet then in Wayland?

No, xsetwacom does not work in Wayland and never will as it is X11 program. I have no idea if other tablet configuration tools will be developed for Wayland. But there should be no problems with using tablets in Wayland. This may be tablet-dependent but at least my Wacom in-screen digitizer is working* and I'm guessing most Wacom  tablets should work at this point.

*There are still some issues in xournal++ where the pointer is sometimes displaced relative to actual location of the pen tip (the pen writes where the tip is, not where the pointer is shown). But generally things work and are on track to working well.

**Comment by LittleHuba** [comment]
Tablet input is handled like any other input through libinput. Libinput is somewhat limited in customizability but provides developers with a stable input system where we do not need to introduce fixes for certain devices. Should your tablet or stylus not work as expected, please talk to the devs of libinput.

You might also be interested in trying out the flag `GDK_BACKEND=wayland` in a Wayland session to use Xournal++ as a native Wayland application. But be aware that this backend is not yet perfect.

**Comment by ttshaw1** [comment]
I seem to have a similar issue as initially posted. Mouse movement and left clicking works fine, but the stylus buttons do nothing in Xournal++. I'm running KDE Plasma Wayland 5.23.3-, kwin version 5.23.3-1 on Arch.  
[debug_input.log](https://github.com/xournalpp/xournalpp/files/7543345/debug_input.log)
[debug_gdk_input.log](https://github.com/xournalpp/xournalpp/files/7543372/debug_gdk_input.log)
[list_devices.txt](https://github.com/xournalpp/xournalpp/files/7543374/list_devices.txt)

Using `libinput debug-events --verbose` it appears that the buttons produce right and middle clicks as expected. It's either an issue of xournal not getting the events from kwin or whatever else is supposed to pass them along from libinput, or the events being passed and xournal not registering them. 
[debug_events.txt](https://github.com/xournalpp/xournalpp/files/7543375/debug_events_xournal_2quirks.txt)

How can I tell if I should bring this to kwin's community?

**Comment by bhennion** [comment]
Fixed in Plasma
