### ISSUE TITLE
Mouse Cursor stays invisible after using pen

### ISSUE THREAD

**Issue by KonstantinHebenstreit** [xournalpp/xournalpp#2920]
**Affects versions :**
 - OS: Linux 20.04
 - (Linux only) Desktop environment: Gnome 3.36, X11
 - Which version of libgtk do you use: 3.22.30
 - Version of Xournal++: 1.0.20
 - Installation method: snap

**Describe the bug**
After writing on the touchscreen of a convertible (HP Envy X360) with a smartpen (HP Pen), I want to use the mouse: The cursor is visible for half second and then disappears, although I continue moving the mouse. I can use the mouse, but I do not the cursor.

**To Reproduce**
1. Activate Preferences > Touchscreen > 'enable internal hand recognition' (bug appears only with this option activated)
2. draw with pen
3. move mouse > cursor not visible

possible 'solution':
4. touch screen with hand
5. move mouse again > cursor is visible

**Expected behavior**
Mouse Cursor should be visible, when moving the mouse - after writing something with pen.

**Screenshots of Problem**
I made a screencast of the problem, but unfortunately in the screencast the cursor is always visible (when I watch the video afterwards)... Any suggestions?

**Additional context**
When I press super key, then move the mouse in the 'overview' it becomes visible and stays visible if I use xournal.
When I just press the super key twice, the coursor is still invisible.

General: If I use two screens, the cursor is also invisible on both of them.

**Comment by personalizedrefrigerator** [comment]
Try again with version [1.1.0+dev](https://github.com/xournalpp/xournalpp/releases/tag/nightly). It might have been fixed since 1.0.20...

**Comment by KonstantinHebenstreit** [comment]
Thanks for the answer and the hint. For the moment I think I will stay with the stable release, since apart from that bug it is working really well. (Had a lot of other bugs two weeks ago, when I had it installed differently.)

**Comment by rolandlo** [comment]
I can't reproduce it, even with the snap package.

**Comment by rolandlo** [comment]
By the way @KonstantinHebenstreit  you can easily test out the 1.1.0+dev version using the Appimage, just [download](https://github.com/xournalpp/xournalpp/releases/tag/nightly), make it executable and run, no installation is needed.

**Comment by KonstantinHebenstreit** [comment]
Thanks for your recommendations :)

I juts tried the 1.1.0+dev, installed with the shell commands from here: 
https://github.com/xournalpp/xournalpp#unstable-ppa

It works better, so I do not have to enable the internal hand recognition!
But if I do, the same bug is still there. just fyi.

I also found out something new: The cursor of the mouse remains as long as the Timeout in Preferences/Touchscreen is set. So if I set it to 5 seconds, the mouse cursor is visible for 5 seconds after I use the pen, then the mouse cursor vanishes.

Thanks! I'll just use the nightly release now. (I had some problems first, but after a reboot everything is fine so far.)
