### ISSUE TITLE
TeX object is not correctly rendered in exported PDF.

### ISSUE THREAD

**Issue by tattsan** [xournalpp/xournalpp#3692]
**Affects versions :**
 - OS: Arch Linux
 - Desktop environment: X11 with xmonad
 - gtk: 3.24.31
 - Version of Xournal++: both 1.1.0 and master.
 - Installation method: both Arch package and built from source.

**Describe the bug**
TikZ picture in TeX object is not correctly rendered in exported PDF.

**To Reproduce**
1. Prepare LaTeX template file which contains '\usepackage{tikz}' .
2. Create a TeX object like this:
```
\begin{tikzpicture} \foreach\i in{0,...,200}{\draw[ultra thin] ({\i/50},0) -- (\i/50,3);} \end{tikzpicture}
```

3. Save the .xopp file, and export as PDF.
4. Compare the exported pdf with the temporary /tmp/xournalpp-?????/tex/tex.pdf. You'll see the line width and the distance between lines are incorrect.

This is  correct picture.
[tex.pdf](https://github.com/xournalpp/xournalpp/files/7798814/tex.pdf)

This is the exported file.
[foo-exp.pdf](https://github.com/xournalpp/xournalpp/files/7798815/foo-exp.pdf)

**Comment by rolandlo** [comment]
Not sure what is going on here, since `pdftocairo -pdf tex.pdf tex_exp.pdf` results in a correct export.

**Comment by tattsan** [comment]
`xournalpp foo.xopp  --export-png-dpi=600  -i foo-exp.png` creates a correct png file.

**Comment by tattsan** [comment]
When you reopen the .xopp file, you'll see the wrong picture first. After about 300 millisecond, the picture will be rendered correctly. So there seems to be  two rendering processes.

https://user-images.githubusercontent.com/6355486/147891837-d6750fdf-b973-4178-a71f-41bd1d68f16b.mp4

When exported to PDF, you'll get the first picture.
When exported to PNG, you'll get the second picture.

**Comment by tattsan** [comment]
I found color emoji fonts are also rendered poorly. In the following sample, I input an emoji char U+1F604 with text input tool.
* This is exported PDF:
[foo-exp.pdf](https://github.com/xournalpp/xournalpp/files/7966168/foo-exp.pdf)
* This is exported PNG (600dpi):
![foo-exp](https://user-images.githubusercontent.com/6355486/151705802-0021fea9-b479-4384-8240-39354962ac2a.png)

**Comment by tattsan** [comment]
The two step rendering mentioned in https://github.com/xournalpp/xournalpp/issues/3692#issuecomment-1003789787 also occurs for the color emoji fonts.

**Comment by tattsan** [comment]
There is a very tedious work around. First, modify `XojCairoPdfExport::exportPage` in  `XojCairoPdfExport.cpp` as follows;
```
 void XojCairoPdfExport::exportPage(size_t page) {
     PageRef p = doc->getPage(page);
 
-     cairo_pdf_surface_set_size(this->surface, p->getWidth(), p->getHeight());
+     cairo_pdf_surface_set_size(this->surface, 10*p->getWidth(), 10*p->getHeight());
+     cairo_scale(this->cr, 10, 10);

    DocumentView view;
```
Then, xournalpp will create a 10x10 times scaled up PDF. Second, you can use `ghostscript` to restore the original size, and you'll get a nicely rendered PDF.

**Comment by tattsan** [comment]
I've found a decent solution for TeX objects, but not yet for ColorEmoji.

**Comment by tattsan** [comment]
I made more simple samples.
* TeX objects: written in plain TeX command only.
 - [tex-sample.xopp.gz](https://github.com/xournalpp/xournalpp/files/8053303/tex-sample.xopp.gz)
 - [tex-wrong.pdf](https://github.com/xournalpp/xournalpp/files/8053304/tex-wrong.pdf)
 - [tex-correct.pdf](https://github.com/xournalpp/xournalpp/files/8053305/tex-correct.pdf)
* Color emoji fonts: needs color emoji fonts, like Noto Color Emoji.
 - [emoji-sample.xopp.gz](https://github.com/xournalpp/xournalpp/files/8053308/emoji-sample.xopp.gz)
 - [emoji-wrong.pdf](https://github.com/xournalpp/xournalpp/files/8053309/emoji-wrong.pdf)
 - [emoji-correct.pdf](https://github.com/xournalpp/xournalpp/files/8053311/emoji-correct.pdf)

In both case, they are rendered as if they are displayed in very low resolution screen.
For the TeX object, this is resolved in #3773 . But I can't find the way to change the behavior of `pango` or `cairo` for color emoji fonts.

**Comment by bhennion** [comment]
Note that .svg exports are also affected.

**Comment by bhennion** [comment]
The emoji issue is actually related to the specific font (Noto Color Emoji), which does not come as vector graphics.
For those rasterized fonts, it seems that Pango infers the DPI from the provided cairo_surface. In the case of a PDF surface, there is not DPI, so it uses the page coordinates unit square as a pixel (we can see in @tattsan's emoji-sample.xopp file that a pixel of the emoji face has size 1 in xournal++'s page coordinates).

Not sure what a good solution would be.

**Comment by bhennion** [comment]
The emoji part of the issue is fixed by #4687.

**Comment by tattsan** [comment]
I applied #4687 to dc39a0a1087ff832cb78d45071598e0a7f3e820f  and tested it. But strangely, I 'venoticed that the emoji-bug was already fixed without #4687!  I couldn't find when it was fixed.

**Comment by bhennion** [comment]
Probably with #4566 then

**Comment by scarlion1** [comment]
I'm still seeing poorly rendered emoji in exported PDF.  Had to type a big emoji in GIMP then copy it as an image, paste into xournalpp, and resize it accordingly.  Fortunately only one character was needed this time.  Was there maybe a regression?  Using Debian v. 1.2.4-1 here w/ GTK v. 3.24.43.

**Comment by tattsan** [comment]
@scarlion1  It may be a problem with cairo or pango, since the problem still occurs even if you use the version that was available at the time the problem was solved. I am using the [workaround]( https://github.com/xournalpp/xournalpp/issues/3692#issuecomment-1029371094) again.

**Comment by tattsan** [comment]
I've found that the bug reappears when the cairo version is 1.18.0 or later.

**Comment by tattsan** [comment]
To use [emoji-workaround](https://github.com/xournalpp/xournalpp/issues/3692#issuecomment-1029371094) with new export-backend #6364, add the following:
```
--- a/src/core/pdf/base/HybridPdfExport.cpp        2025-04-05 15:33:55.294539033 +0900
+++ b/src/core/pdf/base/HybridPdfExport.cpp     2025-04-05 17:15:20.458879026 +0900
@@ -70,12 +70,14 @@
     size_t progress = 0;
     std::vector<OutputPageInfo> overlayToBackgroundIndex;
     overlayToBackgroundIndex.reserve(count);
+    cairo_scale(this->cr, 10, 10);
     for (const auto& e: range) {
         auto max = std::min(e.last, doc->getPageCount() - 1);  // Should be e.last for parsed PageRangeVector
         for (size_t i = e.first; i <= max; i++) {

             PageRef p = doc->getPage(i);
             if (p->isAnnotated() || p->getPdfPageNr() == npos) {
+                cairo_scale(this->cr, 0.1, 0.1);
                 // Pages with only a PDF background and no annotations will be copied directly
                 exportPage(i, false /* omit background if PDF */);
                 overlayToBackgroundIndex.push_back({true, doc->getPage(i)->getPdfPageNr()});
```
Then
1. If you use qpdf for a backend, generated PDF has correct page size and correct content's size. No ghostscript is needed.
2. If you use mupdf for a backend, generated PDF has correct page size but scaled up contents. So you have to prepare scaled up background pdf and substitute the original background file with it before exporting, and should scaled down the generated PDF by ghostscript. (Use ghostscript twice).
3. If you use cairo for a backend, generated PDF has scaled up page size and correct size contents relative to the PDF. So you have to scale down the generated PDF using ghostscript (Use ghostscript once).

So the qpdf backend is useful.

**Comment by tattsan** [comment]
Emoji-workaround with new backends takes long time to export. New rendering method #6385 impoves it.
```
time xournalpp10x10 --export-pdf-backend=qpdf -p foo_qpdf.pdf foo.xopp
64.14s user 0.07s system 99% cpu 1:04.26 total

time xournalpp10x10_fast --export-pdf-backend=qpdf -p foo_qpdf_fast.pdf foo.xopp
21.39s user 0.05s system 99% cpu 21.453 total
```
